# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd
from itertools import product
from evcouplings.couplings import CouplingsModel

#the following code was adapted from https://github.com/debbiemarkslab/EVcouplings/blob/develop/notebooks/model_parameters_mutation_effects.ipynb

def evmutation_predictions(model, wt_sequence, output_loc=None):
    #model is the file location of the EVCouplings model generated by https://evcouplings.org/
    #wt_sequence is the sequence of the wild type protein
    #output_loc is the file location to store the model predictions

    ##generate the input mutation list for EVmutate
    ALL_AAS = ("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y")
    prediction_list = [] # For EVcouplings: e.g., [[(10, 'A', 'V')]]
    all_combos_list = [] # For our MLDE model: e.g., "A10V"

    sequence_length = len(wt_sequence)

    for i in range(sequence_length):
        pos_1_indexed = i + 1
        original_aa = wt_sequence[i]

        for new_aa in ALL_AAS:
            mutation_string = f"{original_aa}{pos_1_indexed}{new_aa}"
            all_combos_list.append(mutation_string)
            
            mutation_tuple = (pos_1_indexed, original_aa, new_aa)
            prediction_list.append([mutation_tuple])
    
    #make predictions using EVmutate
    c = CouplingsModel(model)
    
    predictions = np.empty(len(prediction_list))
    
    for i, mutation in enumerate(prediction_list):
        try:
            predictions[i], _, _ = c.delta_hamiltonian(mutation)
        except Exception as e:
            print(f"Error predicting {mutation}: {e}")
            predictions[i] = np.nan
    
    mutations_dic = {"EVMutations":prediction_list, "Mutations":all_combos_list, "Predictions":predictions}
    output_df = pd.DataFrame(data=mutations_dic)
    
    if output_loc != None:
        output_df.to_csv(output_loc)

    return output_df